### ISSUE TITLE
Authorization Screen in Android

### ISSUE THREAD

**Issue by teraiyamayurcontact** [datatrans/android-sample-app#1]
Hello Guys,
## IOS Method

pc.paymentOptions.showAuthorizationConfirmationScreen = YES;

 i want to display authorization screen to user when transaction is in process with Alias at that time. Need help.

There are no any method found like showAuthorizationConfirmation Screen.

Thanks in advance.

**Comment by dmengelt** [comment]
hi @teraiyamayurcontact 

right. at the moment the android library does not offer this functionality. you have to create such a screen by your own. you have two options to accomplish this:
- before the beginning of an alias payment
- use `PaymentProccess.setManualCompletionEnabled(true)` to receive a callback before the final authorization. There you could show your additional confirmation screen.

hope that helps

**Comment by teraiyamayurcontact** [comment]
Hi domi55,

Thanks for your feedback i understood your point So below attached should be implemented by us or will display from data trans.

Can you please provide your suggestion for same.
- > Also i am facing one more issue credit card scanning with datatrans SDK. Its all avaiable in IOS but not in Android SDK.

Thanks 

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/10277602/14307126/664117fa-fbea-11e5-92df-25b3e361d73d.png)

**Comment by dmengelt** [comment]
Hi @teraiyamayurcontact 

I just updated the [sample app](https://github.com/datatrans/android-sample-app/raw/master/static/datatrans-android-sample.apk) which now shows a confirmation dialog before the final authorisation. This is of course just one way of achieving a similiar behaviour like with iOS.

Regarding credit card scanning. The android library does not come with this feature out of the box. Please have a look at the code of this sample app. You have to manually integrate [card.io](https://github.com/card-io/card.io-Android-SDK) into your app.

**Comment by teraiyamayurcontact** [comment]
Hi domi,

Thanks a lot. i am not able to get transactionid when transaction is complete ? Can you help me ?

**Comment by teraiyamayurcontact** [comment]
Hi domi,

can you help me for above mention question ?

**Comment by teraiyamayurcontact** [comment]
Hi Domi,

can you help me for above mention question ?

**Comment by dmengelt** [comment]
Correct. Currently we do not send the transactionId in the callback. Please configure the "POST URL" hook from within the Webadmin Tool [TEST](https://pilot.datatrans.biz/) / [PROD](https://payment.datatrans.biz/) to receive the transactionId.

**Comment by teraiyamayurcontact** [comment]
OK Thanks
