### ISSUE TITLE
Save Card Option

### ISSUE THREAD

**Issue by teraiyamayurcontact** [datatrans/android-sample-app#4]
Hello Support Team,

i want display store card option to user with Android Platform. But we are not able find method with Data trans sdk.

IOS Method
pc.paymentOptions.returnsCreditCard = DTPaymentReturnsCreditCardSelectableDefaultNo;

Waiting for your feedback.

**Comment by dmengelt** [comment]
this is currently not possible with Android. However you can use the ["uppRememberMe" feature](https://www.datatrans.ch/alias-tokenization):
`merchantProperties.put("uppRememberMe", "yes");`

**Comment by teraiyamayurcontact** [comment]
Thanks Domi Its works fine. again Thanks for your valuable time.
