### ISSUE TITLE
Get postURL fields after successful transaction

### ISSUE THREAD

**Issue by smihajlovski** [datatrans/android-sample-app#5]
Hello domi, 
I would like to know how can I get the transactionID when the transaction is successfully completed in the COMPLETED case?
I have the URLs on https://pilot.datatrans.biz, but how should I implement them?

Best regards,
Stefan

**Comment by dmengelt** [comment]
Hi @smihajlovski 

Sorry for the late reply. You have two possibilities to get the transaction id:

1. Use `paymentProcess.getTransactionId()` in the success callback of the App.
2. Best practice: Handle the POST URL (configured in the webadmin tool) accordingly. Sample payload:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<uppTransactionService version="1">
    <body merchantId="1100004450" testOnly="yes">
        <transaction refno="968927" status="success">
            <uppTransactionId>170217114103313296</uppTransactionId>
            <amount>1000</amount>
            <currency>CHF</currency>
            <pmethod>VIS</pmethod>
            <reqtype>CAA</reqtype>
            <language>en</language>
            <success>
                <authorizationCode>116323372</authorizationCode>
                <acqAuthorizationCode>114116</acqAuthorizationCode>
                <responseCode>01</responseCode>
            </success>
            <userParameters>
                <parameter name="maskedCC">424242xxxxxx4242</parameter>
                <parameter name="sign">30916165706580013</parameter>
                <parameter name="responseCode">01</parameter>
                <parameter name="expy">18</parameter>
                <parameter name="theme">DT2015</parameter>
                <parameter name="expm">12</parameter>
            </userParameters>
        </transaction>
    </body>
</uppTransactionService>
```

**Comment by smihajlovski** [comment]
Hello Domi. 

Thank you for your answer! However, I am using `PaymentProcessAndroid` but there's no `getTransactionId()`.

**Comment by dmengelt** [comment]
Try to use the latest library. Version 2.2.1.
https://pilot.datatrans.biz/showcase/doc/Android_Library.zip

**Comment by smihajlovski** [comment]
Thank you, this way it works!
