### ISSUE TITLE
[Crashed] - DisplayContext, App is crashed when click "Try again"

### ISSUE THREAD

**Issue by khanhnt3010** [datatrans/android-sample-app#8]
I'm facing this issue in my project, and it's also happened in the sample.

When the ErrorDialog is shown, click "Try again" button, app will be crashed
`
ch.datatrans.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.datatrans.android.sample, PID: 27559
    java.lang.NullPointerException
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
        at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
        at ch.datatrans.payment.f.w(f.java:531)
        at ch.datatrans.payment.f.b(f.java:109)
        at ch.datatrans.payment.l.onClick(Unknown Source:2)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:191)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
`

**Comment by dmengelt** [comment]
Hi @khanhnt3010 
Thanks for reporting this. We were able to reproduce this behaviour and will release a new version of the library as soon as possible. I will update this issue once the the new version is available.

**Comment by khanhnt3010** [comment]
Thank you so much @dmengelt 
Waiting for the new release 💯

**Comment by khanhnt3010** [comment]
> Hi @khanhnt3010
> Thanks for reporting this. We were able to reproduce this behaviour and will release a new version of the library as soon as possible. I will update this issue once the the new version is available.

Hi @dmengelt, do we have any solution or workaround way when waiting for new release?

**Comment by dmengelt** [comment]
Hi @khanhnt3010 
For the time being you can use an older version of the SDK: **REMOVED**

We will deploy a new release this week.

**Comment by dmengelt** [comment]
@khanhnt3010 
New SDK for Android available here: https://admin.sandbox.datatrans.com/showcase/doc/Android_Library.zip
Let me know if this fixes the crash.

I removed the link to the 3.5.3 version.

**Comment by khanhnt3010** [comment]
> @khanhnt3010
> New SDK for Android available here: https://admin.sandbox.datatrans.com/showcase/doc/Android_Library.zip
> Let me know if this fixes the crash.
> 
> I removed the link to the 3.5.3 version.

Thank for your update, I tried to replace new sdk version (4.2.0), but I have an issue like this (tried to replace in sample project too):
`[dtapl-4.2.0.aar] /Users/kn/.gradle/caches/transforms-1/files-1.1/dtapl-4.2.0.aar/7e17ba6ce648fa98baf20dedbe2e2abb/AndroidManifest.xml:22:9-58 Error:
	Missing 'package' key attribute on element package at [dtapl-4.2.0.aar] AndroidManifest.xml:22:9-58
[dtapl-4.2.0.aar] /Users/kn/.gradle/caches/transforms-1/files-1.1/dtapl-4.2.0.aar/7e17ba6ce648fa98baf20dedbe2e2abb/AndroidManifest.xml:23:9-61 Error:
	Missing 'package' key attribute on element package at [dtapl-4.2.0.aar] AndroidManifest.xml:23:9-61
[dtapl-4.2.0.aar] /Users/kn/.gradle/caches/transforms-1/files-1.1/dtapl-4.2.0.aar/7e17ba6ce648fa98baf20dedbe2e2abb/AndroidManifest.xml:24:9-61 Error:
	Missing 'package' key attribute on element package at [dtapl-4.2.0.aar] AndroidManifest.xml:24:9-61
[dtapl-4.2.0.aar] /Users/kn/.gradle/caches/transforms-1/files-1.1/dtapl-4.2.0.aar/7e17ba6ce648fa98baf20dedbe2e2abb/AndroidManifest.xml Error:
	Validation failed, exiting`

**Comment by dmengelt** [comment]
@khanhnt3010 please upgrade your android gradle plugin to a version >= 3.5.4

See: https://developer.android.com/studio/releases/gradle-plugin#3-5-0

> 3.5.4 (July 2020)
This minor update supports compatibility with new default settings and features for package visibility in Android 11.
See the 4.0.1 release notes for details.

Also, I updated the sample app from this repository now to use SDK 4.2.0 and it works for me.

**Comment by khanhnt3010** [comment]
Thank you so much @dmengelt, the issue is resolved.
I'm integrating newest version and testing for it.
I will contribute or report if have any problem 👍
